### PR TITLE
fix stuck at theta 0

### PR DESCRIPTION
**Pull request by tianenchong**
This fix a human that consistently stuck at theta 0, a.k.a. persistent yaw, when the initial theta is 0.

### CODE REVIEW

**Comment by luca-della-vedova** [comment]
What is the reasoning behind this change? Is there no way to fix this in the simulation plugins? If I remember correctly I have never seen this issue before the recent changes in crowd simulation.

**Comment by tianenchong** [comment]
Menge has issue with initial orientation with 0 degree. If we don't want to fix this in menge, then we need to avoid setting angle 0 for human in simulation at all cost.

**Comment by luca-della-vedova** [comment]
But still, did this issue appear before the multilevel crowd simulation changes? I don't recall ever seeing it before

**Comment by tianenchong** [comment]
I remember seeing it in single level crowdsim in static loading. The way the loading has changed also plays apart in the angle. Before static loading (loading in sdf), I didn't see it in Fred's dynamic loading during runtime. Not sure if it could be 0 vs 0.f?

**Comment by tianenchong** [comment]
btw, I didn't see it happening in new updated office map even after I revert to original menge, which is strange.

**Comment by tianenchong** [comment]
One way to find out:
revert menge and change the 0.0 in office.world to 0 to see if it makes a difference

**Comment by tianenchong** [comment]
Just checked that it doesn't make a difference. The point is this fix works.

**Comment by luca-della-vedova** [comment]
What I'm trying to understand is the **logic** behind the fix and why this case would happen.
From what I see from a quick glance at the [code](https://github.com/osrf/menge_core/blob/073db597ec7ae12943903dbe8635024908cf8892/src/Menge/MengeCore/Agents/BaseAgent.cpp#L61) `_orient` is supposed to be initialized at (1.0, 0.0) and it seems to indicate a unit vector indicating the direction, so I can't imagine why both values would be set to 0.0 unless we are doing something wrong.

**Comment by tianenchong** [comment]
I haven't dig that deep. I am not sure why the _orient value reduced to 0 along the way despite the initial value of (1.0, 0.0) since I just discovered the 0 issue. Let me spend some time digging deeper.

**Comment by luca-della-vedova** [comment]
Since this is a fork of an upstream library I'm generally reluctant to introduce changes unless strictly necessary (until now the only changes have been in adding colcon compatibility / removing unnecessary files).
No change in the logic / algorithm has been introduced so far.
I'd suggest figuring out why the issue happens, how the values get set and if it is something that we can fix in the way we use the library first.

**Comment by tianenchong** [comment]
Ok, I have done quite a bit of tracing. The _orient is set from preferred velocity (initialized to (1,0), but changes when the _sim starts in the first iteration). As for the changes, where preferred velocity was set is [here](https://github.com/osrf/menge_core/blob/master/src/Menge/MengeCore/resources/NavMeshEdge.cpp#L470) within NavMeshEdge::setClearDirections. Do pay attention to `prefDir` where the preferred velocity is set. Of course, there are a bunch of maths here in this scope that adds on to the complexity. In a nutshell, it is dependent on navmesh, i.e. map. Different maps behave differently depending on their navmesh.

**Comment by luca-della-vedova** [comment]
> Ok, I have done quite a bit of tracing. The _orient is set from preferred velocity (initialized to (1,0), but changes when the _sim starts in the first iteration). As for the changes, where preferred velocity was set is [here](https://github.com/osrf/menge_core/blob/master/src/Menge/MengeCore/resources/NavMeshEdge.cpp#L470) within NavMeshEdge::setClearDirections. Do pay attention to `prefDir` where the preferred velocity is set. Of course, there are a bunch of maths here in this scope that adds on to the complexity. In a nutshell, it is dependent on navmesh, i.e. map. Different maps behave differently depending on their navmesh.

Which of the branches in the if statement you linked is the one that results in assigning the value of 0? Is the input `dir` always different from `[0.0, 0.0]` and it gets reset to 0 in this function?

**Comment by tianenchong** [comment]
The answer is none and it is quite obscure, even for catching the 0. For ordinary case the `NavMeshEdge::setClearDirections` gets called and `prefDir` gets set. However, for case 0, `NavMeshEdge::setClearDirections` is skipped altogether, i.e. it is returned somewhere before this function gets called.

**Comment by luca-della-vedova** [comment]
> However, for case 0, `NavMeshEdge::setClearDirections` is skipped altogether, i.e. it is returned somewhere before this function gets called.

Which means the issue is not in this specific function?
I'll close this for now, I'd suggest nailing down where the problematic assignment is made and either:

- Fixing it in the plugin's side (if possible) or
- Fixing it in the point of assignment

**Pull request closed without merging**
